/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightLossProgramsInMattorRouteImport } from './routes/weight-loss-programs-in-mattor'
import { Route as TransformationsRouteImport } from './routes/transformations'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as StrengthTrainingInMattorRouteImport } from './routes/strength-training-in-mattor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PersonalTrainingInMattorRouteImport } from './routes/personal-training-in-mattor'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as GymInMattorRouteImport } from './routes/gym-in-mattor'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WeightLossProgramsInMattorRoute =
  WeightLossProgramsInMattorRouteImport.update({
    id: '/weight-loss-programs-in-mattor',
    path: '/weight-loss-programs-in-mattor',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransformationsRoute = TransformationsRouteImport.update({
  id: '/transformations',
  path: '/transformations',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const StrengthTrainingInMattorRoute =
  StrengthTrainingInMattorRouteImport.update({
    id: '/strength-training-in-mattor',
    path: '/strength-training-in-mattor',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainingInMattorRoute =
  PersonalTrainingInMattorRouteImport.update({
    id: '/personal-training-in-mattor',
    path: '/personal-training-in-mattor',
    getParentRoute: () => rootRouteImport,
  } as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const GymInMattorRoute = GymInMattorRouteImport.update({
  id: '/gym-in-mattor',
  path: '/gym-in-mattor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gym-in-mattor': typeof GymInMattorRoute
  '/membership': typeof MembershipRoute
  '/personal-training-in-mattor': typeof PersonalTrainingInMattorRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strength-training-in-mattor': typeof StrengthTrainingInMattorRoute
  '/trainers': typeof TrainersRoute
  '/transformations': typeof TransformationsRoute
  '/weight-loss-programs-in-mattor': typeof WeightLossProgramsInMattorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gym-in-mattor': typeof GymInMattorRoute
  '/membership': typeof MembershipRoute
  '/personal-training-in-mattor': typeof PersonalTrainingInMattorRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strength-training-in-mattor': typeof StrengthTrainingInMattorRoute
  '/trainers': typeof TrainersRoute
  '/transformations': typeof TransformationsRoute
  '/weight-loss-programs-in-mattor': typeof WeightLossProgramsInMattorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gym-in-mattor': typeof GymInMattorRoute
  '/membership': typeof MembershipRoute
  '/personal-training-in-mattor': typeof PersonalTrainingInMattorRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strength-training-in-mattor': typeof StrengthTrainingInMattorRoute
  '/trainers': typeof TrainersRoute
  '/transformations': typeof TransformationsRoute
  '/weight-loss-programs-in-mattor': typeof WeightLossProgramsInMattorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/gym-in-mattor'
    | '/membership'
    | '/personal-training-in-mattor'
    | '/services'
    | '/sitemap.xml'
    | '/strength-training-in-mattor'
    | '/trainers'
    | '/transformations'
    | '/weight-loss-programs-in-mattor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/gym-in-mattor'
    | '/membership'
    | '/personal-training-in-mattor'
    | '/services'
    | '/sitemap.xml'
    | '/strength-training-in-mattor'
    | '/trainers'
    | '/transformations'
    | '/weight-loss-programs-in-mattor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/gym-in-mattor'
    | '/membership'
    | '/personal-training-in-mattor'
    | '/services'
    | '/sitemap.xml'
    | '/strength-training-in-mattor'
    | '/trainers'
    | '/transformations'
    | '/weight-loss-programs-in-mattor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GymInMattorRoute: typeof GymInMattorRoute
  MembershipRoute: typeof MembershipRoute
  PersonalTrainingInMattorRoute: typeof PersonalTrainingInMattorRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StrengthTrainingInMattorRoute: typeof StrengthTrainingInMattorRoute
  TrainersRoute: typeof TrainersRoute
  TransformationsRoute: typeof TransformationsRoute
  WeightLossProgramsInMattorRoute: typeof WeightLossProgramsInMattorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight-loss-programs-in-mattor': {
      id: '/weight-loss-programs-in-mattor'
      path: '/weight-loss-programs-in-mattor'
      fullPath: '/weight-loss-programs-in-mattor'
      preLoaderRoute: typeof WeightLossProgramsInMattorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformations': {
      id: '/transformations'
      path: '/transformations'
      fullPath: '/transformations'
      preLoaderRoute: typeof TransformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strength-training-in-mattor': {
      id: '/strength-training-in-mattor'
      path: '/strength-training-in-mattor'
      fullPath: '/strength-training-in-mattor'
      preLoaderRoute: typeof StrengthTrainingInMattorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-training-in-mattor': {
      id: '/personal-training-in-mattor'
      path: '/personal-training-in-mattor'
      fullPath: '/personal-training-in-mattor'
      preLoaderRoute: typeof PersonalTrainingInMattorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-in-mattor': {
      id: '/gym-in-mattor'
      path: '/gym-in-mattor'
      fullPath: '/gym-in-mattor'
      preLoaderRoute: typeof GymInMattorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GymInMattorRoute: GymInMattorRoute,
  MembershipRoute: MembershipRoute,
  PersonalTrainingInMattorRoute: PersonalTrainingInMattorRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StrengthTrainingInMattorRoute: StrengthTrainingInMattorRoute,
  TrainersRoute: TrainersRoute,
  TransformationsRoute: TransformationsRoute,
  WeightLossProgramsInMattorRoute: WeightLossProgramsInMattorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
